<a href="https://colab.research.google.com/github/dyzulk/raisen-app/blob/main/CRAWL_SKRIPSI_DESTIANA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

!sudo apt-get update
!sudo apt-get install -y \
libatk1.0-0 \
libatk-bridge2.0-0 \
libgbm1 \
libasound2 \
libxcomposite1 \
libxdamage1 \
libxrandr2 \
libx11-xcb1 \
libpangocairo-1.0-0 \
libpango-1.0-0 \
libcairo2 \
libgtk-3-0

Hit:1 https://deb.nodesource.com/node_20.x nodistro InRelease
Hit:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:3 https://cli.github.com/packages stable InRelease
Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:5 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:6 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:9 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:10 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libcairo2 is already the newest version (1.16.0-5ubuntu2).
libcairo2 set to manually installed.
libxdamage1 is already the newest version (1:1.1.5-2build2).
libxdamage1 set to manually installed.
libxrandr2 is already the newest version (2:1.5.2-1build1).
libxrandr2 set to manually installed.
libgbm1 is already the newest version (23.2.1-1ubuntu3.1~22.04.3).
libgbm1 set to manually installed.
libpango-1.0-0 is already the newest version (1.50.6+ds-2ubuntu1).
libpango-1.0-0 set to manually installed.
libpangocairo-1.0-0 is already the newest version (1.50.6+ds-2ubuntu1).
libpangocairo-1.0-0 set to manually installed.
libx11-xcb1 is already the newest version (2:1.7.5-1ubuntu0.3).
libx11-xcb1 set to manually installed.
The following additional packages will be installed:
  at-spi2-core gsettings-desktop-schemas libasound2-data libatk1.0-data
  libatspi2.0-0 libgtk-3-bin libgtk-3-common librsvg2-common libxtst6
  session-migration
Suggested packages:
  libasound2-plugins alsa-utils gvfs
Recommended packages:
  alsa-ucm-conf alsa-topology-conf
The following NEW packages will be installed:
  at-spi2-core gsettings-desktop-schemas libatk-bridge2.0-0 libatk1.0-0
  libatk1.0-data libatspi2.0-0 libgtk-3-0 libgtk-3-bin libgtk-3-common
  librsvg2-common libxcomposite1 libxtst6 session-migration
The following packages will be upgraded:
  libasound2 libasound2-data
2 upgraded, 13 newly installed, 0 to remove and 93 not upgraded.
Need to get 4,107 kB of archives.
After this operation, 12.9 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatspi2.0-0 amd64 2.44.0-3 [80.9 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxtst6 amd64 2:1.2.3-1build4 [13.4 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/main amd64 session-migration amd64 0.3.6 [9,774 B]
Get:4 http://archive.ubuntu.com/ubuntu jammy/main amd64 gsettings-desktop-schemas all 42.0-1ubuntu1 [31.1 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/main amd64 at-spi2-core amd64 2.44.0-3 [54.4 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libasound2 amd64 1.2.6.1-1ubuntu1.1 [391 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libasound2-data all 1.2.6.1-1ubuntu1.1 [19.3 kB]
Get:8 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk1.0-data all 2.36.0-3build1 [2,824 B]
Get:9 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk1.0-0 amd64 2.36.0-3build1 [51.9 kB]
Get:10 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk-bridge2.0-0 amd64 2.38.0-3 [66.6 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcomposite1 amd64 1:0.4.5-1build2 [7,192 B]
Get:12 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgtk-3-common all 3.24.33-1ubuntu2.2 [239 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgtk-3-0 amd64 3.24.33-1ubuntu2.2 [3,053 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgtk-3-bin amd64 3.24.33-1ubuntu2.2 [69.6 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 librsvg2-common amd64 2.52.5+dfsg-3ubuntu0.2 [17.7 kB]
Fetched 4,107 kB in 2s (2,201 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 15.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Selecting previously unselected package libatspi2.0-0:amd64.
(Reading database ... 122903 files and directories currently installed.)
Preparing to unpack .../00-libatspi2.0-0_2.44.0-3_amd64.deb ...
Unpacking libatspi2.0-0:amd64 (2.44.0-3) ...
Selecting previously unselected package libxtst6:amd64.
Preparing to unpack .../01-libxtst6_2%3a1.2.3-1build4_amd64.deb ...
Unpacking libxtst6:amd64 (2:1.2.3-1build4) ...
Selecting previously unselected package session-migration.
Preparing to unpack .../02-session-migration_0.3.6_amd64.deb ...
Unpacking session-migration (0.3.6) ...
Selecting previously unselected package gsettings-desktop-schemas.
Preparing to unpack .../03-gsettings-desktop-schemas_42.0-1ubuntu1_all.deb ...
Unpacking gsettings-desktop-schemas (42.0-1ubuntu1) ...
Selecting previously unselected package at-spi2-core.
Preparing to unpack .../04-at-spi2-core_2.44.0-3_amd64.deb ...
Unpacking at-spi2-core (2.44.0-3) ...
Preparing to unpack .../05-libasound2_1.2.6.1-1ubuntu1.1_amd64.deb ...
Unpacking libasound2:amd64 (1.2.6.1-1ubuntu1.1) over (1.2.6.1-1ubuntu1) ...
Preparing to unpack .../06-libasound2-data_1.2.6.1-1ubuntu1.1_all.deb ...
Unpacking libasound2-data (1.2.6.1-1ubuntu1.1) over (1.2.6.1-1ubuntu1) ...
Selecting previously unselected package libatk1.0-data.
Preparing to unpack .../07-libatk1.0-data_2.36.0-3build1_all.deb ...
Unpacking libatk1.0-data (2.36.0-3build1) ...
Selecting previously unselected package libatk1.0-0:amd64.
Preparing to unpack .../08-libatk1.0-0_2.36.0-3build1_amd64.deb ...
Unpacking libatk1.0-0:amd64 (2.36.0-3build1) ...
Selecting previously unselected package libatk-bridge2.0-0:amd64.
Preparing to unpack .../09-libatk-bridge2.0-0_2.38.0-3_amd64.deb ...
Unpacking libatk-bridge2.0-0:amd64 (2.38.0-3) ...
Selecting previously unselected package libxcomposite1:amd64.
Preparing to unpack .../10-libxcomposite1_1%3a0.4.5-1build2_amd64.deb ...
Unpacking libxcomposite1:amd64 (1:0.4.5-1build2) ...
Selecting previously unselected package libgtk-3-common.
Preparing to unpack .../11-libgtk-3-common_3.24.33-1ubuntu2.2_all.deb ...
Unpacking libgtk-3-common (3.24.33-1ubuntu2.2) ...
Selecting previously unselected package libgtk-3-0:amd64.
Preparing to unpack .../12-libgtk-3-0_3.24.33-1ubuntu2.2_amd64.deb ...
Unpacking libgtk-3-0:amd64 (3.24.33-1ubuntu2.2) ...
Selecting previously unselected package libgtk-3-bin.
Preparing to unpack .../13-libgtk-3-bin_3.24.33-1ubuntu2.2_amd64.deb ...
Unpacking libgtk-3-bin (3.24.33-1ubuntu2.2) ...
Selecting previously unselected package librsvg2-common:amd64.
Preparing to unpack .../14-librsvg2-common_2.52.5+dfsg-3ubuntu0.2_amd64.deb ...
Unpacking librsvg2-common:amd64 (2.52.5+dfsg-3ubuntu0.2) ...
Setting up session-migration (0.3.6) ...
Created symlink /etc/systemd/user/graphical-session-pre.target.wants/session-migration.service → /usr/lib/systemd/user/session-migration.service.
Setting up libxtst6:amd64 (2:1.2.3-1build4) ...
Setting up libatspi2.0-0:amd64 (2.44.0-3) ...
Setting up libasound2-data (1.2.6.1-1ubuntu1.1) ...
Setting up librsvg2-common:amd64 (2.52.5+dfsg-3ubuntu0.2) ...
Setting up libatk1.0-data (2.36.0-3build1) ...
Setting up libasound2:amd64 (1.2.6.1-1ubuntu1.1) ...
Setting up libatk1.0-0:amd64 (2.36.0-3build1) ...
Setting up libxcomposite1:amd64 (1:0.4.5-1build2) ...
Setting up libgtk-3-common (3.24.33-1ubuntu2.2) ...
Setting up gsettings-desktop-schemas (42.0-1ubuntu1) ...
Setting up libatk-bridge2.0-0:amd64 (2.38.0-3) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for libgdk-pixbuf-2.0-0:amd64 (2.42.8+dfsg-1ubuntu0.4) ...
Processing triggers for libglib2.0-0:amd64 (2.72.4-0ubuntu2.7) ...
Setting up libgtk-3-0:amd64 (3.24.33-1ubuntu2.2) ...
Processing triggers for libc-bin (2.35-0ubuntu3.11) ...
/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

Setting up libgtk-3-bin (3.24.33-1ubuntu2.2) ...
Setting up at-spi2-core (2.44.0-3) ...

In [ ]:
!apt-get update
!apt-get install -y libatk1.0-0 libatk-bridge2.0-0 libgtk-3-0 libgbm1

Hit:1 https://deb.nodesource.com/node_20.x nodistro InRelease
Hit:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:3 https://cli.github.com/packages stable InRelease
Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:5 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:6 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:8 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:9 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:10 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libatk-bridge2.0-0 is already the newest version (2.38.0-3).
libatk1.0-0 is already the newest version (2.36.0-3build1).
libgbm1 is already the newest version (23.2.1-1ubuntu3.1~22.04.3).
libgtk-3-0 is already the newest version (3.24.33-1ubuntu2.2).
0 upgraded, 0 newly installed, 0 to remove and 93 not upgraded.

In [ ]:
# Crawl Data Twitter dengan tweet-harvest
Twitter_auth_token = "d34c05808ac32d71d9424f982e9862e5e2660e09"

filename = "kelistrikan2024.csv"
search_keyword = "kelistrikan2024 since:2024-01-01 until:2024-12-28 lang:id"
limit = 20000

#jalankan perintah dengan f-string agar variabel terbaca dengan benar
!npx -y tweet-harvest@2.6.1 -o "{filename}" -s "{search_keyword}" --tab "LATEST" -l {limit} --token "{Twitter_auth_token}"

⠙⠹⠸⠼⠴⠦Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


Found existing file ./tweets-data/kelistrikan2024.csv, renaming to ./tweets-data/kelistrikan2024.old.csv

-- Scrolling... (1) (2) (3)
Filling in keywords: kelistrikan2024 since:2024-01-01 until:2024-12-28 lang:id



Your tweets saved to: /content/tweets-data/kelistrikan2024.csv
Total tweets saved: 0

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 1 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 2 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 3 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20)No tweets found for the search criteria
⠙

In [ ]:
import pandas as pd

file_path = f"tweets-data/{filename}"

df = pd.read_csv(file_path, delimiter=",")

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 645 entries, 0 to 644
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   conversation_id_str      645 non-null    int64
 1   created_at               645 non-null    object
 2   favorite_count           645 non-null    int64
 3   full_text                645 non-null    object
 4   id_str                   645 non-null    int64
 5   image_url                59 non-null     object
 6   in_reply_to_screen_name  409 non-null    object
 7   lang                     645 non-null    object
 8   location                 0 non-null      float64
 9   quote_count              645 non-null    int64
 10  reply_count              645 non-null    int64
 11  retweet_count            645 non-null    int64
 12  tweet_url                645 non-null    object
 13  user_id_str              645 non-null    int64
 14  username                 0 non-null      float64
dtypes: float64(2), int64(7), object(6)
memory usage: 75.7+ KB

In [ ]:
df.head(5)

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,2026626831068373037,Wed Feb 25 17:58:27 +0000 2026,0,@sosmedkeras lebih tepatnya sering applu cpns ...,2026718449712734231,NaN,sosmedkeras,in,NaN,0,0,0,https://x.com/undefined/status/202671844971273...,1464168554060783616,NaN
1,2026189135220998421,Wed Feb 25 17:58:27 +0000 2026,0,@oreoorisinil tajam jga ya,2026718449058365640,NaN,oreoorisinil,in,NaN,0,0,0,https://x.com/undefined/status/202671844905836...,2012385290854281217,NaN
2,2026619181186060507,Wed Feb 25 17:58:27 +0000 2026,0,@FinchWeb3 7sGK7o913pWdNsPGvTqPR1MS5eToxqB5S2o...,2026718448596943264,NaN,FinchWeb3,in,NaN,0,0,0,https://x.com/undefined/status/202671844859694...,1807131745936195584,NaN
3,2026708596562735254,Wed Feb 25 17:58:27 +0000 2026,0,@BilackMan par janab endia ko kangluland hi fu...,2026718448194404691,NaN,BilackMan,in,NaN,0,0,0,https://x.com/undefined/status/202671844819440...,1635544372048699392,NaN
4,2026668885773107321,Wed Feb 25 17:58:27 +0000 2026,0,@hon_wamuchomba Naona Hata kws Mututho utarudi...,2026718448194097259,NaN,hon_wamuchomba,in,NaN,0,0,0,https://x.com/undefined/status/202671844819409...,1806370973999927296,NaN

In [ ]:
from google.colab import files

# Use the file_path variable which contains the correct path 'tweets-data/pln.csv'
files.download(file_path)

In [ ]:
!pip install google-play-scraper

Collecting google-play-scraper
  Downloading google_play_scraper-1.2.7-py3-none-any.whl.metadata (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.2/50.2 kB 1.1 MB/s eta 0:00:00
Downloading google_play_scraper-1.2.7-py3-none-any.whl (28 kB)
Installing collected packages: google-play-scraper
Successfully installed google-play-scraper-1.2.7

In [ ]:
from google_play_scraper import app
import pandas as pd
import datetime

In [ ]:
from numpy import result_type
from google_play_scraper import app, reviews, Sort

app_id ='com.icon.pln123'

def get_reviews(app_id, lang='id', count=90000, sort=Sort.NEWEST, filter_score_with=None, filter_device_with=None, continuation_token=None):
    try:
        result, continuation_token = reviews(
            app_id,
            lang=lang,
            country='id',
            sort=sort,
            count=count,
            filter_score_with=filter_score_with,
            filter_device_with=filter_device_with,
            continuation_token=continuation_token
        )

        return result, continuation_token
    except Exception as e:
        print("Error:", e)
        return None, None

reviews_data, continuation_token = get_reviews(app_id)

if reviews_data is not None:
    print ("Jumlah Ulasan : ", len(reviews_data))
    if len(reviews_data) > 0:
        print ("Contoh Ulasan:")
        print (reviews_data[0])
else:
    print ("Tidak dapat mengambil ulasan.")

Jumlah Ulasan :  90000
Contoh Ulasan:
{'reviewId': 'bf6158b3-9f01-4aaa-925b-28fdb06114b9', 'userName': 'Pengguna Google', 'userImage': 'https://play-lh.googleusercontent.com/EGemoI2NTXmTsBVtJqk8jxF9rh8ApRWfsIMQSt2uE4OcpQqbFu7f7NbTK05lx80nuSijCz7sc3a277R67g', 'content': 'bagus dan aman nyaman tinggal dirumah layanan terpenuhi', 'score': 5, 'thumbsUpCount': 0, 'reviewCreatedVersion': '5.2.77', 'at': datetime.datetime(2026, 2, 24, 19, 17, 16), 'replyContent': 'Terima kasih atas dukungannya, Kak. PLN Mobile terus berkembang biar makin fleksibel bantu kamu kapan aja & di mana aja. Yuk rekomendasikan ke kerabat dan keluarga Kk utk download PLN Mobile. :) -IP\n', 'repliedAt': datetime.datetime(2026, 2, 25, 4, 54, 7), 'appVersion': '5.2.77'}

In [ ]:
from os import write
import csv

def export_to_csv(reviews,file_name='hasil_scraper_ulasan_app_pln_mobile.csv'):
    if reviews:
        fieldnames = ['Review ID', 'Username', 'Rating','Review Text', 'Date']

        with open(file_name, mode='w', newline='', encoding='utf-8') as csv_file:
            writer = csv.DictWriter(csv_file, fieldnames=fieldnames)
            writer.writeheader()

            for review in reviews:
                writer.writerow({
                    'Review ID': review['reviewId'],
                    'Username': review['userName'],
                    'Rating': review['score'],
                    'Review Text' : review['content'],
                    'Date' : review['at']
                    })
        print(f"Data berhasil diekspor ke '{file_name}'")
    else:
        print("Tidak ada data ulasan untuk diekspor.")

export_to_csv(reviews_data)

Data berhasil diekspor ke 'hasil_scraper_ulasan_app_pln_mobile.csv'

In [ ]:
import pandas as pd

data = pd.read_csv("hasil_scraper_ulasan_app_pln_mobile.csv")
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90000 entries, 0 to 89999
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Review ID    90000 non-null  object
 1   Username     90000 non-null  object
 2   Rating       90000 non-null  int64
 3   Review Text  90000 non-null  object
 4   Date         90000 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.4+ MB

In [ ]:
data.head(20)

,Review ID,Username,Rating,Review Text,Date
0,bf6158b3-9f01-4aaa-925b-28fdb06114b9,Pengguna Google,5,bagus dan aman nyaman tinggal dirumah layanan ...,2026-02-24 19:17:16
1,fca811ce-856c-40d2-9db8-3cff7ed81f3a,Pengguna Google,5,trimakasih menjadi lebih mudah,2026-02-24 19:05:24
2,5e1506ac-aa23-41fc-a9e3-0771e46baa0b,Pengguna Google,3,sagat bgus,2026-02-24 18:52:17
3,ec39a47e-676c-40b2-8a87-166dfd7618c8,Pengguna Google,1,aplikasi mengecewakan banyak gaya nya.daftar p...,2026-02-24 18:37:09
4,dca1ab73-820b-4307-b19d-69595072e391,Pengguna Google,1,hallo bisa di hapus saja aplikasi ini? aplikas...,2026-02-24 18:33:01
5,616ac763-fc83-4ce0-b62f-6a352b22d89f,Pengguna Google,5,"Pencatatan sistim online,sangat Efektif dan Ef...",2026-02-24 18:00:49
6,200f9639-4f18-4095-845a-65cc719212e9,Pengguna Google,5,dengan pln mobile pelayanan jadi lebih cepat,2026-02-24 17:46:02
7,82698e9a-c249-457b-b0f4-1a593a744f26,Pengguna Google,5,banyak fitur,2026-02-24 17:33:55
8,c4e8cf87-dd9a-4883-b38b-c8b37bcdd41f,Pengguna Google,5,"Pelayanan Cepat leboh mudah, Handal",2026-02-24 17:27:40
9,c96f589f-212a-44ea-aef2-f60b439c3dd2,Pengguna Google,5,sangat puas sekali,2026-02-24 17:21:50
10,a2cc99d2-fcb9-4ec8-b08d-413c40460c28,Pengguna Google,5,sangat terbantu sekali dengan aplikasi pln ini...,2026-02-24 17:12:31
11,22238ab6-48f6-4d85-9c96-b09a938d84aa,Pengguna Google,5,trima kasih dengan pln mobile bayar token tanp...,2026-02-24 16:36:34
12,9e91c332-cf83-478b-b475-9c585e9d5757,Pengguna Google,3,lambat respon dalam perbaikian.,2026-02-24 16:35:48
13,3977c8a6-2a22-4dc6-8011-45bd911db9fd,Pengguna Google,5,Oke,2026-02-24 16:35:41
14,78f22d50-4d4e-44f2-96bd-f9e3f44df98f,Pengguna Google,5,pelayanan cepat,2026-02-24 16:31:08
15,f2192b73-8996-4ec3-a650-ecd73c4c60e8,Pengguna Google,5,pelayan sangat bagus,2026-02-24 16:08:08
16,3f946652-c6e1-47ef-9782-e44fa434fe74,Pengguna Google,5,pke PLN mobile mmg mempermudah kita saat ada t...,2026-02-24 16:07:11
17,4f24769e-4f52-4870-9f2c-ca50b02caf17,Pengguna Google,5,aplikasi pln mobile bagus sangat membantu kelu...,2026-02-24 16:06:15
18,d643e9a1-0841-48bc-8b15-2b3225f1b599,Pengguna Google,5,apk ini yang transparan di saat pelanggan untu...,2026-02-24 15:48:57
19,d45dbc69-a8cd-43e0-9e57-d2d1664acda8,Pengguna Google,5,pln mobile sangat membantu dalam pengisian ula...,2026-02-24 15:46:48

In [ ]:
#perintah untuk mendownload text csv
from google.colab import files

files.download('hasil_scraper_ulasan_app_pln_mobile.csv')